# Generated by Django 3.2 on 2021-10-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Группа предметов')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('doc_or_tool', models.CharField(choices=[('Инструмент', 'Инструмент'), ('Удостоверение', 'Удостоверение')], max_length=64, verbose_name='Тип предмета')),
                ('photo', models.ImageField(blank=True, upload_to='item_group_images', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Группа предметов',
                'verbose_name_plural': 'Группы предметов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя предмета')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='item_images', verbose_name='Фото')),
                ('change_interval', models.SmallIntegerField(default=12, verbose_name='Интервал выдачи')),
                ('test_interval', models.SmallIntegerField(default=12, verbose_name='Интервал проверки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemtypesapp.itemgroupmodel')),
            ],
            options={
                'verbose_name': 'Тип предмета',
                'verbose_name_plural': 'Типы предметов',
                'ordering': ['name'],
            },
        ),
    ]
