# Generated by Django 3.2 on 2021-10-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Город')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
    ]
