# Generated by Django 3.2 on 2021-10-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='city_images'),
        ),
    ]
