# Generated by Django 3.2 on 2021-10-24 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211024_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Организация')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.citymodel')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Подразделение')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.companymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Группа предметов')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('doc_or_tool', models.CharField(max_length=64, verbose_name='Тип предмета')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО сотрудника')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('is_brig', models.BooleanField(default=False, verbose_name='Бригадир')),
                ('is_company_leader', models.BooleanField(default=False, verbose_name='Руководитель орг.')),
                ('is_departament_leader', models.BooleanField(default=False, verbose_name='Руководитель подр.')),
                ('telegram_id', models.IntegerField(default=0, verbose_name='Telegram ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phones', models.TextField(blank=True, verbose_name='Телефоны')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departamentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя предмета')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('change_interval', models.SmallIntegerField(default=12, verbose_name='Интервал выдачи')),
                ('test_interval', models.SmallIntegerField(default=12, verbose_name='Интервал проверки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.itemgroupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('inventory_number', models.CharField(blank=True, max_length=64, verbose_name='Инвентарный номер')),
                ('change_for', models.DateField(verbose_name='Дата выдачи')),
                ('test_for', models.DateField(blank=True, verbose_name='Дата проверки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.itemtypemodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.workermodel')),
            ],
        ),
    ]
