# Generated by Django 3.2 on 2021-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_companymodel_departamentmodel_itemgroupmodel_itemmodel_itemtypemodel_workermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'ordering': ['name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='companymodel',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='departamentmodel',
            options={'ordering': ['name'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='itemgroupmodel',
            options={'ordering': ['name'], 'verbose_name': 'Группа предметов', 'verbose_name_plural': 'Группы предметов'},
        ),
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'ordering': ['worker'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='itemtypemodel',
            options={'ordering': ['name'], 'verbose_name': 'Тип предмета', 'verbose_name_plural': 'Типы предметов'},
        ),
        migrations.AlterModelOptions(
            name='workermodel',
            options={'ordering': ['name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='itemgroupmodel',
            name='doc_or_tool',
            field=models.CharField(choices=[('Инструмент', 'Инструмент'), ('Удостоверение', 'Удостоверение')], max_length=64, verbose_name='Тип предмета'),
        ),
    ]
