# Generated by Django 3.2 on 2021-10-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211024_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='departamentmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='departament_images'),
        ),
        migrations.AlterField(
            model_name='itemgroupmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='item_group_images'),
        ),
        migrations.AlterField(
            model_name='itemtypemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
