# Generated by Django 3.2 on 2021-10-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211024_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='city_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='company_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='departamentmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='departament_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='itemgroupmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='item_group_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='itemtypemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='item_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
