# Generated by Django 3.2 on 2021-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211024_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='brig',
            field=models.IntegerField(default=0, verbose_name='ФИО Бригадира'),
        ),
        migrations.AddField(
            model_name='workermodel',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Табельный номер'),
        ),
    ]
