# Generated by Django 3.2 on 2021-10-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_workermodel_brig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='brig',
            field=models.ForeignKey(default=1, limit_choices_to={'is_brig': True}, on_delete=django.db.models.deletion.PROTECT, to='mainapp.workermodel'),
        ),
    ]
