# Generated by Django 3.2 on 2021-10-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_workermodel_brig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='brig',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_brig': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.workermodel'),
        ),
    ]
