# Generated by Django 3.2 on 2021-10-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_workermodel_brig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='change_for',
            field=models.DateField(blank=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='test_for',
            field=models.DateField(verbose_name='Дата проверки'),
        ),
    ]
