# Generated by Django 3.2 on 2021-10-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemtypesapp', '0001_initial'),
        ('workersapp', '0001_initial'),
        ('mainapp', '0012_auto_20211025_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='departamentmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='itemtypemodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='workermodel',
            name='brig',
        ),
        migrations.RemoveField(
            model_name='workermodel',
            name='departament',
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemtypesapp.itemtypemodel'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workersapp.workermodel'),
        ),
        migrations.DeleteModel(
            name='CityModel',
        ),
        migrations.DeleteModel(
            name='CompanyModel',
        ),
        migrations.DeleteModel(
            name='DepartamentModel',
        ),
        migrations.DeleteModel(
            name='ItemGroupModel',
        ),
        migrations.DeleteModel(
            name='ItemTypeModel',
        ),
        migrations.DeleteModel(
            name='WorkerModel',
        ),
    ]
