# Generated by Django 3.2 on 2021-10-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Филиал')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='city_images', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Организация')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='company_images', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workersapp.citymodel')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Подразделение')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='departament_images', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workersapp.companymodel')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО сотрудника')),
                ('number', models.IntegerField(default=0, verbose_name='Табельный номер')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, upload_to='photo', verbose_name='Фото')),
                ('is_brig', models.BooleanField(default=False, verbose_name='Бригадир')),
                ('is_company_leader', models.BooleanField(default=False, verbose_name='Руководитель орг.')),
                ('is_departament_leader', models.BooleanField(default=False, verbose_name='Руководитель подр.')),
                ('telegram_id', models.IntegerField(default=0, verbose_name='Telegram ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phones', models.TextField(blank=True, verbose_name='Телефоны')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('brig', models.ForeignKey(blank=True, limit_choices_to={'is_brig': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='workersapp.workermodel')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workersapp.departamentmodel')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
    ]
