# Generated by Django 3.2 on 2021-10-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermodel',
            name='photo',
        ),
    ]
