# Generated by Django 3.2 on 2021-10-29 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workersapp', '0002_remove_workermodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workermodel',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='workermodel',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='workermodel',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
