# Generated by Django 3.2 on 2021-10-31 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workersapp', '0003_auto_20211029_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='linked_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'linked_worker': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
