# Generated by Django 3.2 on 2021-10-31 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workersapp', '0004_alter_workermodel_linked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='linked_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_linked': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
