# Generated by Django 3.2 on 2021-10-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workersapp', '0002_remove_workermodel_photo'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=256, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linked_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workersapp.workermodel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
