# Generated by Django 3.2 on 2021-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phones',
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Табельный номер'),
        ),
    ]
