# Generated by Django 3.2 on 2021-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20211029_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
    ]
